# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Intalling module in /frontend'
  inputs:
    command: 'install'
    workingDir: 'frontend'
- task: Npm@1
  displayName: 'Building module in /frontend'
  inputs:
    command: 'custom'
    workingDir: 'frontend'
    customCommand: 'start'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'frontend'
    Contents: 'frontend/build/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'