# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main # Trigger on changes to the main branch

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  workingDirectory: $(System.DefaultWorkingDirectory)/frontend
  displayName: 'npm install and build'

# Deploy to Azure Static Web Apps (or similar)
- task: AzureStaticWebApp@0
  inputs:
    app_location: 'frontend/dist' # Path to built frontend
    azure_static_web_apps_api_token: $(STATIC_WEB_APP_TOKEN) # Add token in pipeline variables
  displayName: 'Deploy Frontend'