name: Build and deploy ASP.Net Core app to an Azure Web App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'kcurr'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/backend'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '7.0'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: ./backend/backend
         
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore and Build Project'
      run: |
        echo "Starting dotnet restore and build in directory: $PWD"
        dotnet restore
        dotnet build --configuration Release --output ./output
        echo "Build completed. Checking output directory..."
        if [ -d "./output" ]; then
        echo "Output directory created at: $(realpath ./output)"
        ls -la ./output
        else
        echo "ERROR: Output directory was not created."
        exit 1
        fi

    - name: 'Log Current Directory and Output Path'
      run: |
        echo "Current directory: $PWD"
        echo "Listing all files in current directory recursively:"
        ls -laR
        echo "Verifying absolute path for output directory:"
        OUTPUT_PATH=$(realpath ./output)
        echo "Absolute path to output directory: $OUTPUT_PATH"

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ github.workspace }}/backend/backend/output
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
    - name: Export environment variables for App Service
      run: |
        echo "CloudMersiveApiKey=${{ secrets.CLOUDMERSIVE_API_KEY }}" >> $GITHUB_ENV
        echo "CurrencyApiApiKey=${{ secrets.CURRENCY_API_API_KEY }}" >> $GITHUB_ENV
        echo "CurrencyBeaconApiKey0=${{ secrets.CURRENCY_BEACON_API_KEY_0 }}" >> $GITHUB_ENV
        echo "CurrencyBeaconApiKey1=${{ secrets.CURRENCY_BEACON_API_KEY_1 }}" >> $GITHUB_ENV
        echo "CurrencyBeaconApiKey2=${{ secrets.CURRENCY_BEACON_API_KEY_2 }}" >> $GITHUB_ENV
        echo "RapidApiApiKey0=${{ secrets.RAPID_API_API_KEY_0 }}" >> $GITHUB_ENV
        echo "RapidApiApiKey1=${{ secrets.RAPID_API_API_KEY_1 }}" >> $GITHUB_ENV
        echo "RapidApiApiKey2=${{ secrets.RAPID_API_API_KEY_2 }}" >> $GITHUB_ENV
